# Exploratory data analysis
## openfoodfacts + USDA database

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# Load the dataset: the paths depend on the path of the unzipped data 'food_dbs.zip'
# adjust the paths as necessary, default - as below - assumes the data is in the same directory as this notebook
df_off = pd.read_csv('data/off_nutrition_clean.csv')
df_usda =pd.read_csv('data/usda_nutrition_clean.csv')

/var/folders/yz/grwlw1c90b1dbggwlxd8jf200000gn/T/ipykernel_63782/1771437061.py:6: DtypeWarning: Columns (0: item_id) have mixed types. Specify dtype option on import or set low_memory=False.
  df_off = pd.read_csv('data/off_nutrition_clean.csv')
/var/folders/yz/grwlw1c90b1dbggwlxd8jf200000gn/T/ipykernel_63782/1771437061.py:7: DtypeWarning: Columns (0: portion_description) have mixed types. Specify dtype option on import or set low_memory=False.
  df_usda =pd.read_csv('data/usda_nutrition_clean.csv')

In [ ]:
df_off.columns

Index(['item_id', 'item_name', 'brand', 'kcal_100g', 'protein_100g',
       'carbs_100g', 'fat_100g', 'serving_size', 'quantity', 'source'],
      dtype='str')

In [ ]:
df_usda.columns

Index(['item_id', 'item_name', 'brand', 'kcal_100g', 'protein_100g',
       'carbs_100g', 'fat_100g', 'portion_description', 'gram_weight',
       'source'],
      dtype='str')

In [ ]:
df_off.info()

<class 'pandas.DataFrame'>
RangeIndex: 66341 entries, 0 to 66340
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   item_id       66341 non-null  object
 1   item_name     66341 non-null  str
 2   brand         56777 non-null  str
 3   kcal_100g     66341 non-null  float64
 4   protein_100g  66341 non-null  float64
 5   carbs_100g    66341 non-null  float64
 6   fat_100g      66341 non-null  float64
 7   serving_size  47711 non-null  str
 8   quantity      27935 non-null  str
 9   source        66341 non-null  str
dtypes: float64(4), object(1), str(5)
memory usage: 5.1+ MB

In [ ]:
df_usda.info()

<class 'pandas.DataFrame'>
RangeIndex: 1817628 entries, 0 to 1817627
Data columns (total 10 columns):
 #   Column               Dtype
---  ------               -----
 0   item_id              int64
 1   item_name            str
 2   brand                float64
 3   kcal_100g            float64
 4   protein_100g         float64
 5   carbs_100g           float64
 6   fat_100g             float64
 7   portion_description  str
 8   gram_weight          float64
 9   source               str
dtypes: float64(6), int64(1), str(3)
memory usage: 138.7 MB

In [ ]:
print(df_usda.gram_weight.isna().sum())
print(df_usda.portion_description.isna().sum())

1804600
1804656

In [ ]:
# sum of the NAN per column of df_usda
print(df_usda.isna().sum())

item_id                      0
item_name                    0
brand                  1817628
kcal_100g                    0
protein_100g                 0
carbs_100g                   0
fat_100g                     0
portion_description    1804656
gram_weight            1804600
source                       0
dtype: int64

In [ ]:
df_usda.describe()

,item_id,brand,kcal_100g,protein_100g,carbs_100g,fat_100g,gram_weight
count,1.817628e+06,0.0,1.817628e+06,1.817628e+06,1.817628e+06,1.817628e+06,13028.000000
mean,1.617401e+06,NaN,2.672501e+02,7.458632e+00,3.307498e+01,1.220373e+01,237.026819
std,6.986552e+05,NaN,1.850154e+02,8.957361e+00,2.906477e+01,1.616996e+01,317.012038
min,1.675120e+05,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.100000
25%,1.130349e+06,NaN,9.100000e+01,7.100000e-01,6.670000e+00,0.000000e+00,85.000000
50%,1.677964e+06,NaN,2.670000e+02,4.760000e+00,2.333000e+01,5.560000e+00,170.000000
75%,2.176503e+06,NaN,4.000000e+02,1.064000e+01,5.962000e+01,1.940000e+01,250.000000
max,2.747651e+06,NaN,9.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02,6000.000000

In [ ]:
df_usda_clean = df_usda.drop(columns=['gram_weight', 'portion_description'])

In [ ]:
df_usda_clean.item_name.head(20)

0                               PARMESAN PEPPERCORN DIP
1                               STAR WARS HOT COCOA MIX
2                     GOOD MEADOW, CLASSIC COCONUT CAKE
3                                  SOURDOUGH MULTIGRAIN
4            REDUCED SODIUM CHICKEN BROTH, RICH CHICKEN
5                                 OLD WORLD, PITA BREAD
6          AMERICA'S CHOICE, DELUXE RED VELVET CAKE MIX
7                         CHEESE MERCHANTS, GOAT CHEESE
8                                                  CAKE
9                                                 STOCK
10                            ORGANIC UNSWEETENED COCOA
11    FINLANDIA, ALL NATURAL CHEESE SNACK, SHARP CHE...
12                                         QUESO PANELA
13               GWALTNEY, HARDWOOD SMOKED SLICED BACON
14                               AMERICAN SLICES CHEESE
15                                 SEASONED COATING MIX
16                          GUGGISBERG, FARMER'S CHEESE
17     ANTONINA'S ARTISAN BAKERY, DOUBLE CHOCOLATE CAKE
18                      GOURMET ITALIAN PIZZA CRUST MIX
19                                   ORGANIC FLAT FRUIT
Name: item_name, dtype: str

In [ ]:
# find items with only lower case letters in item_name
df_usda_clean[df_usda_clean.item_name.str.islower()].item_name.head(20)

3753                                         popcorn chicken
6775                                         popcorn chicken
85659      natural, gluten free pattie made with all thig...
87436                 1st and 2nd portions1 serving = 3 pcs.
196776                                   3/4"" diced chicken
273441                1st and 2nd portions1 serving = 3 pcs.
323594                                  breast meat fritters
342559                                  breast meat fritters
464244                                   3/4"" diced chicken
501934     natural, gluten free pattie made with all thig...
501935                1st and 2nd portions1 serving = 3 pcs.
557033                                   whole grain patties
686889                  natural - no artificial ingredients.
716727     natural, gluten free pattie made with all thig...
730022     51% whole grain crust with blueberry bits, stu...
801362                            marketing copy coming soon
906286                                     1 serving = 3 oz.
922737     51% whole grain crust suffed with a blend of m...
1028005                          sausage egg cheese sandwich
1169754    51% whole grain crust with blueberry bits, stu...
Name: item_name, dtype: str

In [ ]:
df_off.head(20)

,item_id,item_name,brand,kcal_100g,protein_100g,carbs_100g,fat_100g,serving_size,quantity,source
0,103783001,greek yogurt,Chobani,86.666667,7.333333,10.666667,1.666667,NaN,NaN,openfoodfacts
1,107972030,Fajita Chicken W/ Wholegrain Rice,Fuelhub,97.227723,10.891089,10.297030,1.049505,1 portion (505 g),NaN,openfoodfacts
2,1247,Shake Mix Vanilla Flavour,Herbalife,376.000000,36.000000,42.000000,7.200000,100.0g,NaN,openfoodfacts
3,127534563,German fine bread,NaN,263.000000,7.020000,52.630000,3.510000,2 SLICES (57 g),NaN,openfoodfacts
4,1328,Harvest whole wheat bread,"Trader Joe's, E.Leclerc",232.558140,11.627907,41.860465,4.651163,NaN,NaN,openfoodfacts
5,136010485,Jalapeno Cheddar Pepperoni,Beaverlodge Butcher Shop,163.636364,18.181818,1.818182,9.090909,1 portion (55 g),NaN,openfoodfacts
6,1526,Sourdough Bread,Trader Joe's,214.285714,8.390992,59.118050,1.403875,1 portion (56 g),24 oz,openfoodfacts
7,1564,Fromage blanc pêche,NaN,98.000000,4.600000,7.600000,3.300000,NaN,NaN,openfoodfacts
8,1977,Cracked Wheat Sourdough Bread,Trader Joe's,211.538462,7.692308,46.153846,0.961538,1 slice (52 g),24 oz,openfoodfacts
9,200003146,Oven Baked Prawn Cocktail,Walkers,94.000000,1.100000,15.000000,2.800000,22 g,NaN,openfoodfacts
10,200008498,Walkers Crisp Famously Worcester Sauce Crisps,Walkers,508.126195,6.300000,53.000000,29.000000,25 g,NaN,openfoodfacts
11,200010279,Seriously Salt & Vinegar,Walkers,512.000000,6.000000,52.000000,29.200000,1 bag (25 g),NaN,openfoodfacts
12,2204,MK Seed Mix,NaN,474.000000,27.000000,0.800000,35.000000,NaN,680 g,openfoodfacts
13,236555909,"Bakers Best, White Bread",Wise Woodworks,235.000000,8.820000,50.000000,1.470000,1.2 ONZ (34 g),NaN,openfoodfacts
14,236598784,"Bakers Best, Rye Bread",Wise Woodworks,256.000000,7.690000,53.850000,2.560000,1 SLICE (39 g),NaN,openfoodfacts
15,260814065,Gluten free multigrain bread,Trader Joe's,156.010057,2.376447,33.502577,1.909592,36 g,360 g,openfoodfacts
16,300001023,Saucisson sec au poivre les fines tranches,NaN,380.000000,23.600000,1.600000,31.000000,NaN,NaN,openfoodfacts
17,300001056,Salami de dinde,NaN,297.000000,17.100000,5.400000,23.000000,NaN,NaN,openfoodfacts
18,3117,Bonbons de chocolat assortis,NaN,491.000000,6.230000,39.620000,33.740000,NaN,NaN,openfoodfacts
19,400075290,citroenijs merengue,NaN,177.000000,4.000000,24.000000,6.500000,NaN,NaN,openfoodfacts

In [ ]:
df_usda_clean.head(10)

,item_id,item_name,brand,kcal_100g,protein_100g,carbs_100g,fat_100g,source
0,1251280,PARMESAN PEPPERCORN DIP,NaN,188.0,12.50,6.25,15.62,usda
1,1251668,STAR WARS HOT COCOA MIX,NaN,393.0,0.00,96.43,0.00,usda
2,1251760,"GOOD MEADOW, CLASSIC COCONUT CAKE",NaN,395.0,2.63,59.21,17.11,usda
3,1251788,SOURDOUGH MULTIGRAIN,NaN,246.0,7.02,47.37,1.75,usda
4,1252048,"REDUCED SODIUM CHICKEN BROTH, RICH CHICKEN",NaN,6.0,1.25,0.42,0.00,usda
5,1252144,"OLD WORLD, PITA BREAD",NaN,278.0,11.11,52.78,2.78,usda
6,1252149,"AMERICA'S CHOICE, DELUXE RED VELVET CAKE MIX",NaN,385.0,2.56,79.49,7.69,usda
7,1252177,"CHEESE MERCHANTS, GOAT CHEESE",NaN,250.0,17.86,3.57,17.86,usda
8,1252189,CAKE,NaN,429.0,3.57,39.29,28.57,usda
9,1252191,STOCK,NaN,22.0,0.00,1.77,0.88,usda

In [ ]:
df_usda_copy = df_usda_clean.copy()
df_usda_copy = df_usda_copy.drop(columns=['item_id', 'brand',])

df_off_copy = df_off.copy()
df_off_copy = df_off_copy.drop(columns=['item_id', 'brand', 'serving_size', 'quantity'])

In [ ]:
df_usda_copy.columns

Index(['item_name', 'kcal_100g', 'protein_100g', 'carbs_100g', 'fat_100g',
       'source'],
      dtype='str')

In [ ]:
df_off_copy.columns

Index(['item_name', 'kcal_100g', 'protein_100g', 'carbs_100g', 'fat_100g',
       'source'],
      dtype='str')

In [ ]:
df_full = pd.concat([df_usda_copy, df_off_copy], ignore_index=True)

In [ ]:
# make all item_name lower case
df_full['item_name'] = df_full['item_name'].str.lower()

In [ ]:
df_full.item_name[11]

'finlandia, all natural cheese snack, sharp cheddar'

In [ ]:
# df_full.item_name with only entries without ' '
df_oneword = df_full[df_full.item_name.str.contains(' ') == False]

In [ ]:
print('Unique one-word item names:', df_oneword.item_name.nunique())
print('Entries in single word item names:', df_oneword.shape[0])

Unique one-word item names: 5370
Entries in single word item names: 39433

In [ ]:
# search for strin 'bolognese' in item_name
df_full[df_full.item_name.str.contains('cheesecake')].item_name.head(20)

264                                    cheesecake sampler
366                          chocolate lover's cheesecake
404            good & de lish, raspberry swirl cheesecake
406             jon dongire, dark cherry swirl cheesecake
450                                            cheesecake
475     atlanta cheesecake company, cheesecake bites, ...
2009                      chocolate cheesecake, chocolate
2758                                           cheesecake
2822               thick & rich new york style cheesecake
2836              traditional 1 d'lectable cheesecake bar
2918    cinnamon cheesecake rich cinnamon graham swirl...
2936    premium strawberry cheesecake ice cream with a...
3546                                           cheesecake
3568                                    cream cheesecakes
3966    gold emblem, select, gourmet european milk cho...
4330                                   cheesecake, cherry
5482      chocolate truffle cheesecake, chocolate truffle
6395                                           cheesecake
6904                nice!, gingerbread cheesecake cookies
6975                       creamstyle assorted cheesecake
Name: item_name, dtype: str

In [ ]:
df_oneword.source.value_counts()

source
usda             32961
openfoodfacts     6472
Name: count, dtype: int64

In [ ]:

df_oneword[df_oneword['source'] == 'openfoodfacts'].nunique()

item_name       4089
kcal_100g       1796
protein_100g    1247
carbs_100g      1665
fat_100g        1358
source             1
dtype: int64

In [ ]:
df_oneword[df_oneword['source'] == 'usda'].nunique()

item_name       1732
kcal_100g        611
protein_100g    1017
carbs_100g      2109
fat_100g        1318
source             1
dtype: int64

In [ ]:
df_full[df_full['item_name'] == 'avocado']

,item_name,kcal_100g,protein_100g,carbs_100g,fat_100g,source
61961,avocado,192.0,0.0,0.0,15.38,usda
693373,avocado,167.0,0.0,10.0,15.00,usda
1877319,avocado,31.0,0.9,4.0,0.80,openfoodfacts

In [ ]:
df_full[df_full['item_name'] == 'apple']

,item_name,kcal_100g,protein_100g,carbs_100g,fat_100g,source
189583,apple,46.000000,0.000000,11.670000,0.000000,usda
455065,apple,54.000000,0.410000,14.050000,0.000000,usda
460648,apple,54.000000,0.410000,14.050000,0.000000,usda
568206,apple,54.000000,0.410000,14.050000,0.000000,usda
615861,apple,150.000000,0.000000,35.000000,0.000000,usda
819259,apple,52.000000,0.000000,14.290000,0.650000,usda
842339,apple,46.000000,0.000000,11.670000,0.000000,usda
966149,apple,46.000000,0.000000,11.670000,0.000000,usda
1164600,apple,46.000000,0.000000,11.670000,0.000000,usda
1392114,apple,46.000000,0.000000,11.670000,0.000000,usda
1616688,apple,54.000000,0.410000,14.050000,0.000000,usda
1845431,apple,16.142558,18.448637,18.448637,18.448637,openfoodfacts

In [ ]:
df_full[df_full['item_name'] == 'apple'].describe()

        kcal_100g  protein_100g  carbs_100g   fat_100g
count   12.000000     12.000000   12.000000  12.000000
mean    55.345213      1.674053   15.190720   1.591553
std     31.552944      5.286305    6.543666   5.311893
min     16.142558      0.000000   11.670000   0.000000
25%     46.000000      0.000000   11.670000   0.000000
50%     49.000000      0.000000   14.050000   0.000000
75%     54.000000      0.410000   14.110000   0.000000
max    150.000000     18.448637   35.000000  18.448637

In [ ]:
df_full[df_full['item_name'] == 'avocado'].describe()

        kcal_100g  protein_100g  carbs_100g   fat_100g
count    3.000000      3.000000    3.000000   3.000000
mean   130.000000      0.300000    4.666667  10.393333
std     86.642945      0.519615    5.033223   8.310243
min     31.000000      0.000000    0.000000   0.800000
25%     99.000000      0.000000    2.000000   7.900000
50%    167.000000      0.000000    4.000000  15.000000
75%    179.500000      0.450000    7.000000  15.190000
max    192.000000      0.900000   10.000000  15.380000

In [33]:
df_full.info()

<class 'pandas.DataFrame'>
RangeIndex: 1883969 entries, 0 to 1883968
Data columns (total 6 columns):
 #   Column        Dtype
---  ------        -----
 0   item_name     str
 1   kcal_100g     float64
 2   protein_100g  float64
 3   carbs_100g    float64
 4   fat_100g      float64
 5   source        str
dtypes: float64(4), str(2)
memory usage: 86.2 MB

In [ ]:
df_word_counts = df_full.copy()
df_word_counts['word_count'] = df_word_counts['item_name'].str.count(' ') + 1